"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { SubpageShell } from "../components/SubpageShell";

type CartItem = { productId: number; slug: string; name: string; sku: string; priceText: string; thumbnailUrl: string; quantity: number };

export default function CartPage() {
  const [items, setItems] = useState<CartItem[]>([]);
  const [form, setForm] = useState({ customerName: "", customerPhone: "", customerEmail: "", shippingAddress: "", installationAddress: "" });
  const [notice, setNotice] = useState("");
  useEffect(() => { const read = () => { try { setItems(JSON.parse(window.localStorage.getItem("rhinory_cart") || "[]")); } catch { setItems([]); } }; read(); window.addEventListener("rhinory-cart-updated", read); return () => window.removeEventListener("rhinory-cart-updated", read); }, []);
  const update = (slug: string, quantity: number) => { const next = items.map((item) => item.slug === slug ? { ...item, quantity: Math.max(1, Math.min(99, quantity)) } : item); setItems(next); window.localStorage.setItem("rhinory_cart", JSON.stringify(next)); };
  const remove = (slug: string) => { const next = items.filter((item) => item.slug !== slug); setItems(next); window.localStorage.setItem("rhinory_cart", JSON.stringify(next)); };
  const estimated = useMemo(() => items.reduce((sum, item) => { const match = item.priceText.replaceAll(",", "").match(/[0-9]+/); return sum + (match ? Number(match[0]) : 0) * item.quantity; }, 0), [items]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, items }) }); const body = await response.json().catch(() => ({})); setNotice(response.ok ? body.message || "요청이 접수되었습니다." : body.error || "요청을 접수하지 못했습니다."); if (response.ok) { setItems([]); window.localStorage.removeItem("rhinory_cart"); setForm({ customerName: "", customerPhone: "", customerEmail: "", shippingAddress: "", installationAddress: "" }); } };
  return <SubpageShell title="장바구니" kicker="CART / QUOTE REQUEST"><div className="cart-page page-frame">{items.length ? <><div className="cart-layout"><section className="cart-items"><div className="section-heading"><div><p className="eyebrow">YOUR SELECTION</p><h2>선택한 상품</h2></div><span>{items.length}개 상품</span></div>{items.map((item) => <article className="cart-item" key={item.slug}><img src={item.thumbnailUrl} alt={item.name} /><div><p className="product-meta">{item.sku}</p><h3>{item.name}</h3><p>{item.priceText}</p><div className="cart-item-actions"><label>수량 <input type="number" min="1" max="99" value={item.quantity} onChange={(event) => update(item.slug, Number(event.target.value))} /></label><button type="button" onClick={() => remove(item.slug)}>삭제</button></div></div></article>)}</section><form className="cart-form" onSubmit={submit}><p className="eyebrow">QUOTE / DELIVERY</p><h2>설치·배송 정보를 남겨주세요.</h2><p>현재는 결제 전 견적 요청으로 접수됩니다. 담당자가 재고, 설치 가능 지역, 최종 비용을 확인해 연락드립니다.</p><label>성함<input required value={form.customerName} onChange={(event) => setForm({ ...form, customerName: event.target.value })} /></label><label>연락처<input required value={form.customerPhone} onChange={(event) => setForm({ ...form, customerPhone: event.target.value })} /></label><label>이메일<input type="email" value={form.customerEmail} onChange={(event) => setForm({ ...form, customerEmail: event.target.value })} /></label><label>배송 주소<input value={form.shippingAddress} onChange={(event) => setForm({ ...form, shippingAddress: event.target.value })} /></label><label>설치 주소<textarea rows={3} value={form.installationAddress} onChange={(event) => setForm({ ...form, installationAddress: event.target.value })} /></label><div className="cart-total"><span>예상 상품 금액</span><strong>{estimated.toLocaleString()}원~</strong></div><button className="dark-button" type="submit">견적 요청하기 →</button>{notice && <p className="form-notice">{notice}</p>}</form></div></> : <div className="empty-page"><p className="eyebrow">YOUR SELECTION</p><h2>장바구니가 비어 있습니다.</h2><p>상품 상세에서 필요한 제품을 담고 설치 조건을 함께 요청해보세요.</p><Link href="/category/gate" className="dark-button">상품 둘러보기 →</Link></div>}</div></SubpageShell>;
}
